theme: minima
repository: zapkon/homepage.github.io  
plugins: ['jekyll-github-metadata', 'jekyll-seo-tag']
timezone: Europe/Berlin

# defaults
# https://jekyllrb.com/docs/configuration/#front-matter-defaults
defaults:
  - scope:
      path: ""
    values:
      image: https://bilder.bild.de/fotos/carlos-crazy-charly-lehder-rivas-drogenboss-lebt-jetzt-in-deutschem-pflegeheim-201458208-71376390/Bild/2.bild.jpg

# SEO
# https://github.com/jekyll/jekyll-seo-tag
title: Project of Konstantin Zapolski
description: Some projects
logo: https://www.bild.de/news/ausland/news-ausland/van-gogh-aus-museum-geklaut-fotos-aufgetaucht-71373298.bild.html
twitter:
  username: redaxo
  
linkedin: 
  username: zapp
social:
  name: Friends Of REDAXO
  links:
    - https://www.linkedin.com/feed
    - https://www.linkedin.com/feed
